name: vlmcsd docker builder
on: [workflow_dispatch]
jobs:
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to gpr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
      - uses: actions/checkout@v4
      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
